va=int(input("ingrese un numero:"))
va1=int(input("ingrese otro numero:"))
ope= va + va1
print("la suma de los numeros es:",ope)

print("EJERCICIO 1")

va2=int(input("ingrese un numero:"))
va3=int(input("ingrese otro numero:"))
ope1= va2 - va3
print("la resta de los numeros es:",ope1)

print("EJERCICIO 2")

va4=int(input("ingrese un numero:"))
va5=int(input("ingrese otro numero:"))
ope2= va4 * va5
print("la multiplicacion de los numeros es:",ope2)

print("EJERCICIO 3")

va6=int(input("ingrese un numero:"))
va7=int(input("ingrese otro numero:"))
ope3= va6 / va7
print("la division de los numeros es:",ope3)

print("EJERCICIO 4")

nombre=input("ingrese su nombre:")
nombre2=input("ingrese su apellido:")
print("hola",nombre +  " "  + nombre2,"mucho gusto")

print("EJERCICIO 5")

nombre3=input("ingrese su nombre:")
print("la primera letra de su nombre es:",nombre3[0])

print("EJERCICIO 6")

paa=input("!ingrese una palabra")
print("la primera letra de la palabra es:",paa[-1])

print("EJERCICIO 7")

pa1=input("ingrese una palabra")
print("la ultima letra de la palabra es:",pa1[-1])

print("EJERCICIO 8")

base=int(input("ingrese la base del rectangulo:"))
altura=int(input("ingrese la altura del rectangulo:"))
area=base*altura
print("Señor usurario: el area del rectangulo es:",area)

print("EJERCICIO 9")

caal=int(input("ingresemsu su fecha de nacimiento:"))
cal1=int(input("ingrese el año actual:"))
ope10=cal1-caal
print("su edad es:",ope10)

print("EJERCICIO 10")

co=input("ingrese su usuario")
dom=input("ingrese su dominio")
print("su correo es:",co + "@" + dom)

print("EJERCICIO 11")

nom=input("ingrese su nombre:")
print("tu nombre tiene",len(nom),"letras")

print("EJERCICIO 12")

nomm=input("ingrese su nombre")
print("tu nombre tiene",len(nomm),"letras")
pal1=input("ingrese una palabra")
pal2=input("ingrese otra palabra")
print("la union de sus palabras es:",pal1 + " " + pal2)

print("EJERCICIO13")

pala=input("ingrese una palabra")
print=("la segunda letra de la palabra es:",pala[1])

print("EJERCICIO14")

palab=input("ingrese una palabra")
print("Las 3 primeras letras de su palabra es,:",palab[0:3])

print("EJERCICIO15")

palabr=input("ingrese una palabra")
print("Las letras de su palabra en orden inverso es:",palabr[::-1])

print("EJERCICIO 16")

numer=int(input("ingrese un numero"))
numer2=int(input("ingrese otro numero"))
print("la suma la resta y la multiplicacion de sus numeros es:",numer+numer2,numer-numer2,numer*numer2)

print("EJERCICIO 17") 

n22=int(input("ingrese un numero"))
operr=("el doble de su numero es:",n22*2)
print(operr)

print("EJERCICIO 18")

n33=int(input("ingrese un numero"))
operrr=("la mitad de su numero es:",n33/2)
print(operrr)  

print("EJERCICIO 19")

frase=input("ingrese una frase")
print("los caracteres de su frase son:",len(frase) , "caracteres")

print("EJERCICIO 20")

palabraaa=input("ingrese una palabra")
print(palabraaa + palabraaa + palabraaa)

print("EJERCICIO  21")

ingrese=input("ingrese una palabra")
print("Lad dos primeras letras y la dos ultimas letras de su palabra son:",ingrese[0:2],ingrese[-2])

print("EJERCICIO 22")

letrras=input("ingrese una palabra")
print("la letra del medio de su palabra es:",letrras[2:3])

print("EJERCICIO 23")

fraa0=input("ingrese una frase")
print("los 10 primeros caracteres de su frase son:",fraa0[0:10])

print("EJERCICIO 24")

ejerciicio=input("ingrese un numero que desea potenciarlo")
print("su numero elevado solo con multiplicacion es:",ejerciicio*ejerciicio)

print("EJERCICIO 25")

A=int(input("Señor Usuario ingrese un numero"))
B=int(input("Señor Usuario Porfavor ingrese otro numero"))
res25= (A*(A>=B))+(B*(A<B))
print("el mayor de los dos numeros es:",res25)
print("EJERCICIO 26")

edad=int(input("Señor Usuario ingrese su edad"))
print("has vivido aproximadamente:",edad*365,"dias")

print("EJERCICIO 27")

palala=input("ingrese la palabra ladra")
print(palala[0])
print(palala[1])
print(palala[2])
print(palala[3])
print(palala[4])
print(palala[5])

print("EJERCICIO 28")


PALA=input("ingrese una palabra")
print("su palabra tiene mas de 5 letras:",len(PALA)>5)
print("su palabra tiene menos de 5 letras:",len(PALA)<5)

print("EJERCICIO 29")

NUM=int(input("ingrese un numero"))
print("su numero multiplicado por 10 es:",NUM*10)

print("EJERCICIO 30")

PALALALA=input("ingrese una palabra")
print("su palabra en mayusculas es:",PALALALA.upper())
print("su palabra en minusculas es:",PALALALA.lower())


















